name: tag push

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  check-changed-file:
    name: Check changed-file
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959 # v42
        with:
          files: "app/**"
 changed:
   name: changed
    needs: check-changed-file
    if: needs.check-changed-file.outputs.has-changed-related-files == 'true'
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
     - run: echo "changed"
  no_changed:
    name: no changed
    needs: check-changed-file
    if: needs.check-changed-file.outputs.has-changed-related-files == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: no changed
        run: echo "no changed"
