name: Create Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set new release tag
        env:
          TZ: 'Asia/Tokyo'
        run: |
          release_datetime=$(date +'%Y%m%d-%H%M')
          echo "new_release_tag=v$release_datetime" >> $GITHUB_ENV
      - name: Create Release
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{repo}/releases
          repo: ${{ github.repository }}
          tag_name: ${{ env.new_release_tag }}
          target_commitish: main
          name: ${{ env.new_release_tag }}
          generate_release_notes: true
