name: Create Release
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: check release tag
        id: new_release_tag
        run: |
          release_commit=$( git rev-parse HEAD^ )
          release_tag=$( git tag -l --contains $release_commit )
          echo "new_release_tag=v$release_tag" >> $GITHUB_OUTPUT
      - name: Create Release
        if: ${{ steps.new_release_tag.outputs.new_release_tag }} != ""
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{repo}/releases
          repo: ${{ github.repository }}
          tag_name: ${{ steps.new_release_tag.outputs.new_release_tag }}
          target_commitish: main
          name: ${{ steps.new_release_tag.outputs.new_release_tag }}
          generate_release_notes: true
