name: Dependabot fetch metadata
on: pull_request

permissions:
  pull-requests: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check context
        run: |
            echo `${{ github.actor }}`
  dependabot:
    #実験したいので自分の名前でも通るようにする
    if: ${{ github.actor == 'dependabot[bot]' }} || ${{ github.actor == 'Kiryuanzu' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo Dependabot metadata
        run: |
          echo "${{ toJSON(steps.metadata.outputs) }}"
