name: tag push

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  release-tag-create-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: get release date
        id: release_date
        env:
          TZ: "Asia/Tokyo"
        run: |
          release_datetime=$(date +'%Y%m%d-%H%M')
          echo "new_release_tag=v$release_datetime" >> $GITHUB_OUTPUT
      - run: |
          git show ${{ github.event.pull_request.head.sha }}
          git tag ${{ steps.release_date.outputs.new_release_tag }} ${{ github.event.pull_request.head.sha }}
          git show ${{ steps.release_date.outputs.new_release_tag }}
          git push origin ${{ steps.release_date.outputs.new_release_tag }}
